using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuantityMeasurement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAuditTriggerPostgres : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "SystemAudit" (
                    "LogId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Id" uuid NULL,
                    "ActionType" text NOT NULL CHECK ("ActionType" IN ('INSERT', 'UPDATE', 'DELETE', 'UNKNOWN')),
                    "ActionDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "OldValue" jsonb NULL,
                    "NewValue" jsonb NULL
                );
                """
            );

            migrationBuilder.Sql(
                """
                CREATE OR REPLACE FUNCTION fn_system_audit_histories()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    action_type text;
                BEGIN
                    action_type := COALESCE(TG_OP, 'UNKNOWN');

                    IF action_type = 'INSERT' THEN
                        INSERT INTO "SystemAudit" ("Id", "ActionType", "ActionDate", "OldValue", "NewValue")
                        VALUES (NEW."Id", action_type, NOW(), NULL, to_jsonb(NEW));
                        RETURN NEW;
                    ELSIF action_type = 'UPDATE' THEN
                        INSERT INTO "SystemAudit" ("Id", "ActionType", "ActionDate", "OldValue", "NewValue")
                        VALUES (NEW."Id", action_type, NOW(), to_jsonb(OLD), to_jsonb(NEW));
                        RETURN NEW;
                    ELSIF action_type = 'DELETE' THEN
                        INSERT INTO "SystemAudit" ("Id", "ActionType", "ActionDate", "OldValue", "NewValue")
                        VALUES (OLD."Id", action_type, NOW(), to_jsonb(OLD), NULL);
                        RETURN OLD;
                    END IF;

                    INSERT INTO "SystemAudit" ("Id", "ActionType", "ActionDate", "OldValue", "NewValue")
                    VALUES (NULL, 'UNKNOWN', NOW(), NULL, NULL);

                    RETURN NULL;
                END;
                $$;
                """
            );

            migrationBuilder.Sql(
                """
                DROP TRIGGER IF EXISTS trg_system_audit ON "Histories";

                CREATE TRIGGER trg_system_audit
                AFTER INSERT OR UPDATE OR DELETE ON "Histories"
                FOR EACH ROW
                EXECUTE FUNCTION fn_system_audit_histories();
                """
            );

            migrationBuilder.Sql("REVOKE UPDATE, DELETE ON \"SystemAudit\" FROM PUBLIC;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TRIGGER IF EXISTS trg_system_audit ON \"Histories\";");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS fn_system_audit_histories();");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"SystemAudit\";");
        }
    }
}
